version: "3.8"
services:
  app:
    container_name: docker-node-mongo-app
    image: node
    build: .
    links:
      - mongo
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo/exampledb
      - PORT=4000
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
  mongo:
    container_name: docker-node-mongo-database
    image: mongo
    ports:
      - "27107:27107"